services:
  - type: web
    name: platform-python
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 8080
      - key: PYTHONUNBUFFERED
        value: "1"
